export const FormObject = {
  personalInformation: {
    firstName: '',
    middleName: '',
    lastName: '',
    address: '',
    city: '',
    state: '',
    zip: '',
    phone: '',
    email: '',
    legal: '',
    veteran: '',
    background: '', // background check
  },
  position: {
    position: '',
    startDate: '',
    salary: '',
    employment: '',
  },
  education: {
    schoolName: [{}, {}, {}, {}],
    schoolLocation: [{}, {}, {}, {}],
    class: [{}, {}, {}, {}],
    degree: [{}, {}, {}, {}],
    major: [{}, {}, {}, {}],
  },
  references: {
    referenceName: [{}, {}, {}, {}],
    referenceTitle: [{}, {}, {}, {}],
    referenceCompany: [{}, {}, {}, {}],
    referencePhone: [{}, {}, {}, {}],
  },
  employmentHistory: {
    employers: [
      {
        employerName: '',
        jobTitle: '',
        datesEmployed: '',
        workPhone: '',
        startingPay: '',
        endingPay: '',
        employerAddress: '',
        employerCity: '',
        employerState: '',
        employerZip: '',
      },
    ],
  },
  signature: {
    name: '',
    date: '',
    signature: '',
  },
};

export const proObject = {
  firstName: 'Carl',
  middleName: 'Andrew',
  lastName: 'Palumbo',
  address: '710 Jefferson St',
  city: 'Tremont',
  state: 'Ohio',
  zip: '44113',
  phone: '6144620098',
  email: 'C@gmail.com',
  legal: 'no',
  veteran: 'yes',
  background: 'yes',
  position: 'default,Any open position',
  startDate: '02012024',
  salary: '75,000',
  employment: 'Full-time',
  schoolName1: 'Kent State University',
  schoolName2: '',
  schoolName3: '',
  schoolName4: '',
  schoolLocation1: 'Kent, OH',
  schoolLocation2: '',
  schoolLocation3: '',
  schoolLocation4: '',
  year: '2017',
  degree: 'Comp',
  major1: 'Lasers',
  major2: '',
  major3: '',
  major4: '',
  referenceName1: 'Darain Bennett',
  referenceTitle1: 'CFO ',
  referenceCompany1: 'Legal Aid Society of Cleveland',
  referencePhone1: '216-687-1900',
  referenceName2: '',
  referenceTitle2: '',
  referenceCompany2: '',
  referencePhone2: '',
  referenceName3: '',
  referenceTitle3: '',
  referenceCompany3: '',
  referencePhone3: '',
  referenceName4: '',
  referenceTitle4: '',
  referenceCompany4: '',
  referencePhone4: '',
  employerName1: 'Bulk Solutions',
  jobTitle1: 'King of the World',
  datesEmployed1: '01012020 - 01012021',
  workPhone1: '456-789-1234',
  startingPay1: '50,000',
  endingPay1: '65,000',
  employerAddress1: '1710 E 9th St',
  employerCity1: 'Cleveland',
  employerState1: 'OH',
  employerZip1: '44114',
  employerName2: 'Dinkos Tacos',
  jobTitle2: 'Taco Artist',
  datesEmployed2: '01012018 - 01012020',
  workPhone2: '216-555-5555',
  startingPay2: '10,000',
  endingPay2: '50,000',
  employerAddress2: '1710 E 9th St',
  employerCity2: 'Cleveland',
  employerState2: 'OH',
  employerZip2: '44114',
  employerName3: 'Bearcat Solutions',
  jobTitle3: 'King of the World',
  datesEmployed3: '01012020 - 01012021',
  workPhone3: '456-789-1234',
  startingPay3: '50,000',
  endingPay3: '65,000',
  employerAddress3: '1710 E 9th St',
  employerCity3: 'Cleveland',
  employerState3: 'OH',
  employerZip3: '44114',
  employerName4: 'Dinkos Tacos',
  jobTitle4: 'Taco Artist',
  datesEmployed4: '01012018 - 01012020',
  workPhone4: '216-555-5555',
  startingPay4: '10,000',
  endingPay4: '50,000',
  employerAddress4: '1710 E 9th St',
  employerCity4: 'Cleveland',
  employerState4: 'OH',
  employerZip4: '44114',
  printedName: 'Carl Palumbo',
  date: '01012024',
  signature: 'Carl Palumbo',
};
