backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: jobs
    label: Jobs
    folder: jobs
    create: true
    fields:
      - { name: path, Label: Path }
      - { name: postDate, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
