backend:
  name: github
  repo: iangoodnight/bulk-careers
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: jobs
    label: Jobs
    folder: jobs
    create: true
    fields:
      - name: templateKey
        label: "Template Key"
        widget: hidden
        default: Job
      - { name: postDate, label: Date, widget: datetime }
      - { name: active, label: Active, widget: boolean, default: false }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
