backend:
  name: github
  repo: iangoodnight/bulk-careers
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: jobs
    label: Jobs
    folder: jobs
    create: true
    slug:
      encoding: "ascii"
      clean_accents: true
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: "job-post" }
      - { name: postDate, label: Date, widget: datetime }
      - { name: active, label: Active, widget: boolean }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
